spring.application.name=auth

server.port=8081

# Database
#spring.datasource.url=jdbc:mysql://mysql:3306/auth_db
#spring.datasource.username=root    // all are defined in the Docker image only
#spring.datasource.password=Mypswrdsql@76
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=Mypswrdsql@76
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Trace 100% of requests
management.tracing.sampling.probability=1.0

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]