#spring.application.name=wallet
#
#server.port=8082
#  # Database
#spring.datasource.username=root
#spring.datasource.password=Mypswrdsql@76
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  # JPA
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#  # JWT
#jwt.secret=abhinavKumarIsAVeryGoodGuy.HeLovesHerButSheMightNotKnowThatAbhinavLovesHer
#jwt.access-expiration=600000
#jwt.refresh-expiration=1200000
#
#  # Kafka Producer
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.add.type.headers=false
#
#  # Tracing
#management.tracing.sampling.probability=1.0
#
#logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
#
#spring.kafka.template.observation-enabled=true
#spring.kafka.listener.observation-enabled=true